# Generated by Django 5.2.1 on 2025-05-17 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0002_rename_user_name_user_user_username_income_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="income",
            old_name="user_ID",
            new_name="user",
        ),
    ]
