# Generated by Django 5.2.1 on 2025-05-18 11:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0003_rename_user_id_income_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="income_frequency",
            field=models.CharField(default="Monthly", max_length=200),
        ),
        migrations.AddField(
            model_name="income",
            name="income_source",
            field=models.CharField(default="Work", max_length=200),
        ),
        migrations.AddField(
            model_name="income",
            name="income_startDate",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
