# Generated by Django 5.2.1 on 2025-05-22 11:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_income_income_frequency_income_income_source_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="income",
            name="income_addDate",
            field=models.DateField(default=datetime.date.today),
        ),
    ]
