# Generated by Django 5.2.1 on 2025-06-15 21:47

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_income_income_adddate"),
    ]

    operations = [
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_category",
                    models.CharField(default="Entertainment", max_length=200),
                ),
                ("expense_source", models.CharField(default="N/A", max_length=200)),
                ("expense_value", models.IntegerField(default=0)),
                (
                    "expense_frequency",
                    models.CharField(default="One-off", max_length=200),
                ),
                ("expense_startDate", models.DateField(default=datetime.date.today)),
                ("expense_addDate", models.DateField(default=datetime.date.today)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finance.user"
                    ),
                ),
            ],
        ),
    ]
