# Generated by Django 5.2.1 on 2025-06-16 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_expense"),
    ]

    operations = [
        migrations.RenameField(
            model_name="expense",
            old_name="expense_addDate",
            new_name="addDate",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="expense_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="expense_frequency",
            new_name="frequency",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="expense_source",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="expense_startDate",
            new_name="startDate",
        ),
        migrations.RenameField(
            model_name="expense",
            old_name="expense_value",
            new_name="value",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="income_addDate",
            new_name="addDate",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="income_frequency",
            new_name="frequency",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="income_source",
            new_name="source",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="income_startDate",
            new_name="startDate",
        ),
        migrations.RenameField(
            model_name="income",
            old_name="income_value",
            new_name="value",
        ),
    ]
