# Generated by Django 5.2.1 on 2025-06-16 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_rename_expense_adddate_expense_adddate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="frequency",
            field=models.CharField(default="Monthly", max_length=200),
        ),
        migrations.AlterField(
            model_name="income",
            name="source",
            field=models.CharField(default="N/A", max_length=200),
        ),
    ]
