# Generated by Django 5.2.1 on 2025-06-16 10:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0008_alter_expense_frequency_alter_income_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("frequency", models.CharField(default="Monthly", max_length=200)),
                ("startDate", models.DateField(default=datetime.date.today)),
                ("addDate", models.DateField(default=datetime.date.today)),
                ("category", models.CharField(default="Entertainment", max_length=200)),
                ("remainingValue", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="finance.user"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
