# Generated by Django 5.2.1 on 2025-07-20 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0010_remove_budget_frequency_budget_yearlyvalue"),
    ]

    operations = [
        migrations.RenameField(
            model_name="budget",
            old_name="remainingValue",
            new_name="remainingValueMonth",
        ),
        migrations.AddField(
            model_name="budget",
            name="remainingValueYear",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="budget",
            name="yearlyValue",
            field=models.IntegerField(default=0),
        ),
    ]
