# Generated by Django 5.2.1 on 2025-10-30 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0011_rename_remainingvalue_budget_remainingvaluemonth_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlyFinances",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calendarMonth", models.CharField(default="January", max_length=200)),
                ("calendarYear", models.CharField(default="2025", max_length=200)),
                ("totalExpenses", models.IntegerField(default=0)),
                ("totalIncome", models.IntegerField(default=0)),
            ],
        ),
    ]
