# Generated by Django 5.2.1 on 2025-10-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0012_monthlyfinances"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MonthlyFinances",
        ),
    ]
