# Generated by Django 5.2.1 on 2025-10-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0014_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="type",
            field=models.CharField(default="Month", max_length=200),
        ),
    ]
