# Generated by Django 5.2.1 on 2025-10-31 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0015_report_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="report",
            old_name="type",
            new_name="reportType",
        ),
    ]
