# Generated by Django 5.2.1 on 2025-11-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0016_rename_type_report_reporttype"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_username",
        ),
        migrations.AddField(
            model_name="user",
            name="isPrimaryUser",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="password", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="username", max_length=200),
        ),
    ]
